### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by kev123456** [Jumpat/SegmentAnythingin3D#1]
Thanks for the great work! Do you have an ETA on when the code would be released?

**Comment by Jumpat** [comment]
Thanks for your interest! We will release the code as soon as it is complete and easy to follow. We hope to release it by mid-to-late May, but possibly by June at the latest. Please feel free to contact us if you have any other question.☺️

**Comment by yosun** [comment]
You are on my Google Calendar! 

[![Image from Gyazo](https://i.gyazo.com/fc0f52eb4fa86b3ac5429fe1e41102d7.png)](https://gyazo.com/fc0f52eb4fa86b3ac5429fe1e41102d7)

**Comment by liupichuang** [comment]
Thanks for the great work! Do you have an ETA on when the code would be released

**Comment by Jumpat** [comment]
Thanks for your interest. The code will be released this weekend.🥳
