### ISSUE TITLE
Does it work for the model produced by nerfstudio?

### ISSUE THREAD

**Issue by XinyueZ** [Jumpat/SegmentAnythingin3D#10]

**Comment by Jumpat** [comment]
Currently this code for SA3D only supports the provided nerf model. But in principle SA3D can support different kinds of NeRF.

**Comment by XinyueZ** [comment]
@Jumpat thank you.
Would you mind showing me where the changes could be applied to the other NeRFs? I just want to ensure that the code is implemented effectively.

**Comment by XinyueZ** [comment]
@Zanue Thank you for the reply. I would like to know if it is possible to use pre-trained models like `nerfacto` with `SA3D`. I have created a model using `nerfacto` and I want to fine-tune it using `SA3D`. I am unsure of where to start or if it is currently not possible. Do you have any suggestions? Thank you very much in advance.

**Comment by Zanue** [comment]
Thank you for your interest in our work! Currently `SA3D` cannot be directly applied to `nerfacto`, and we are planning to make `nerfstudio` support `SA3D` in a few weeks.

**Comment by FarahSaeed** [comment]
Hi

Just wanted to know... if it is integrated in nerfstudio by now. Thanks!

**Comment by Jumpat** [comment]
We have been trying, but it appears to be a hard work🤣. Thanks for your patience.

**Comment by FarahSaeed** [comment]
Thanks.

**Comment by XinyueZ** [comment]
But is it possible to let the SA3D support `nerfacto` in first? 
Just my opinion.

**Comment by Jumpat** [comment]
This is exactly what we are working on now!👍

**Comment by XinyueZ** [comment]
OK, I am really looking forwards to the support of `nerfacto`.

**Comment by RonnyVelastegui2018** [comment]
Hi,

Just wanted to know if it is integrated with nerfstudio already :)

Thanks!

**Comment by Zanue** [comment]
We have released the nerfstudio-version `SA3D` in the branch `nerfstudio-version`. Currently it only supports text prompts as input. Feel free to ask questions!
