### ISSUE TITLE
Is it posssible to run that code on CPU because I am facing problem in mmcv.

### ISSUE THREAD

**Issue by ibtehajali67** [Jumpat/SegmentAnythingin3D#12]
Can you please share detail regarding cpu

**Comment by Jumpat** [comment]
We haven’t test this code on cpu previously. The mmcv is only used for config loading and requires no gpu. We will check whether we can abandon mmcv and test this code on cpu later. Hope this may help.

**Comment by Jumpat** [comment]
Currently the dependency on mmcv is removed. Hope it may help.
