### ISSUE TITLE
Running on remote server

### ISSUE THREAD

**Issue by FarahSaeed** [Jumpat/SegmentAnythingin3D#13]
Hi 

Thanks for the useful code. 

Can it be possible to run without gui as I am running on linux remote server. I guess it cannot have a gui there.

Thanks a lot.

**Comment by Jumpat** [comment]
Thanks for your interest! Our gui does not depend on the support of screen. It is based on the server and you can just forward the port to your local client and check it on 'http://127.0.0.1:8050' with the browser.

**Comment by FarahSaeed** [comment]
Thanks.

**Comment by FarahSaeed** [comment]
Hi can we change the port. Thanks.
