### ISSUE TITLE
Without the GUI

### ISSUE THREAD

**Issue by kaiaa7** [Jumpat/SegmentAnythingin3D#16]
Hi, thank you very much for your great work!

Can you provide the code  for segmentation without the GUI? Because I want to learn more intuitively how the code for segmentation is used.

**Comment by Jumpat** [comment]
Thanks for your interest! Without the GUI, the selection of prompts and masks seems to be strange. That's why we only realize the GUI scripts temporarily. We may release a GUI-free script in the future nerfstudio version.

**Comment by Jumpat** [comment]
Currently we have released a new version, i.e., SA3D-GS. This version adapts SA3D to 3D Gaussians and currently it does not have a GUI. You can check the new branch for GUI-free SA3D now!
