### ISSUE TITLE
Mesh extraction

### ISSUE THREAD

**Issue by TuluhanAkbulut** [Jumpat/SegmentAnythingin3D#19]
Hello,

How can I extract the mesh of the object after segmentation?

Thank you

**Comment by Jumpat** [comment]
SA3D does not provide the scripts for converting the NeRF to mesh, but there are some possible solutions for this (i.e. marching cube). There are also some other studies about extracting mesh from NeRF like [nerf2mesh](https://github.com/ashawkey/nerf2mesh) and [BakedSDF](https://bakedsdf.github.io/). Hope this may help you.
