### ISSUE TITLE
Evaluation on NVOS

### ISSUE THREAD

**Issue by akhdanfadh** [Jumpat/SegmentAnythingin3D#20]
Hi, thank you for your amazing work. Could you add elaborate on how you load and test the NVOS dataset?

NVOS dataset itself uses the undistort version of LLFF (see README.MD on [their dataset](https://jason718.github.io/nvos/)) from [here](https://github.com/nex-mpi/nex-code/). I'm not sure whether I need to train the NeRF models on that undistort LLFF dataset, or maybe can I just use the LLFF dataset directly and use only the masks and scribbles from NVOS?

Also, do you plan to add your codes on how you evaluate those masks and scribbles? Even better if you plan to add your evaluation code such as your metric calculation (mIoU and Acc)!
I would greatly appreciate it!

**Comment by Jumpat** [comment]
Hello! Thanks for your interest! You can just use the vanilla LLFF dataset for evaluation.
In fact, our code has gone through a thorough refactoring. The code supporting evaluation is very dirty and different from the current version. Temporarily, we do not have a schedule for releasing the old version. This may depend on the future plan of our team (currently busy in integrating SA3D into nerfstudio). 
Moreover, the metric calculation is relatively easy (mIoU = TP / (FN + TP + FP), Acc = (TP + TN) / (TP + FP + TN + FN)).
If you try to reimplement the evaluation by yourself, please let me know if you meet any problem! Hope this may help you!

**Comment by akhdanfadh** [comment]
Thank you for the clarification. Integrating SA3D into nerfstudio would be insane!
I'll close this issue for now and if I have any problem implementing the evaluation, I'll ask here again.
