### ISSUE TITLE
Could not find a backend to open `./logs/llff/fern/render_video_fine_last/video.rgb.mp4`` with iomode `wI`.

### ISSUE THREAD

**Issue by D6561** [Jumpat/SegmentAnythingin3D#22]
thanks for your great jobs!
but i meet some problem when i run "python run.py --config=configs/llff/fern.py --stop_at=20000 --render_video --i_weights=10000"
<img width="667" alt="image" src="https://github.com/Jumpat/SegmentAnythingin3D/assets/95771187/ef1407f8-5256-4e6d-a016-8d47d03b21ff">
Actually, i have install the imageio==2.22.2 and i could not found the mp4 under the folder "render_video_fine_last" .

**Comment by Jumpat** [comment]
Hello! Thanks for your interests.
I guess the imageio[ffmpeg] is different from imageio. Have you tried the “pip install imageio[ffmpeg]” instruction?

**Comment by D6561** [comment]
THX！ the problem solved
