### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by ari1337an** [Jumpat/SegmentAnythingin3D#24]
After running `python run.py` or `python run_seg_gui.py` the following error showing:

In a separate GUI:
![Error Image GUI](https://github.com/Jumpat/SegmentAnythingin3D/assets/36262263/6346f029-d2bd-4d90-9da7-8e5399c9180b)

In the command line:
![Error In Command Line](https://github.com/Jumpat/SegmentAnythingin3D/assets/36262263/bf7f97e9-4dea-4cb0-a2c3-a0a7b5bdcbe7)

My conda env list (generated using `conda list > file.txt`):
| Package Name              | Version       | Build          | Channel       |
|---------------------------|---------------|----------------|---------------|
| addict                    | 2.4.0         | pypi_0         | pypi          |
| blinker                   | 1.6.2         | pypi_0         | pypi          |
| brotli                    | 1.0.9         | pypi_0         | pypi          |
| bzip2                     | 1.0.8         | h8ffe710_4     | conda-forge   |
| ca-certificates           | 2023.7.22     | h56e8100_0     | conda-forge   |
| certifi                   | 2023.7.22     | pyhd8ed1ab_0   | conda-forge   |
| charset-normalizer        | 2.1.1         | pypi_0         | pypi          |
| click                     | 8.1.6         | pypi_0         | pypi          |
| colorama                  | 0.4.6         | pypi_0         | pypi          |
| contourpy                 | 1.1.0         | pypi_0         | pypi          |
| cycler                    | 0.11.0        | pypi_0         | pypi          |
| dash                      | 2.6.2         | pypi_0         | pypi          |
| dash-core-components      | 2.0.0         | pypi_0         | pypi          |
| dash-html-components      | 2.0.0         | pypi_0         | pypi          |
| dash-table                | 5.0.0         | pypi_0         | pypi          |
| filelock                  | 3.9.0         | pypi_0         | pypi          |
| flask                     | 2.3.2         | pypi_0         | pypi          |
| flask-compress            | 1.13          | pypi_0         | pypi          |
| fonttools                 | 4.42.0        | pypi_0         | pypi          |
| fsspec                    | 2023.6.0      | pypi_0         | pypi          |
| huggingface-hub           | 0.14.1        | pypi_0         | pypi          |
| idna                      | 3.4           | pypi_0         | pypi          |
| imageio                   | 2.22.2        | pypi_0         | pypi          |
| importlib-metadata        | 6.8.0         | pypi_0         | pypi          |
| itsdangerous              | 2.1.2         | pypi_0         | pypi          |
| jinja2                    | 3.1.2         | pypi_0         | pypi          |
| kiwisolver                | 1.4.4         | pypi_0         | pypi          |
| libffi                    | 3.4.2         | h8ffe710_5     | conda-forge   |
| libsqlite                 | 3.42.0        | hcfcfb64_0     | conda-forge   |
| libzlib                   | 1.2.13        | hcfcfb64_5     | conda-forge   |
| lpips                     | 0.1.4         | pypi_0         | pypi          |
| markupsafe                | 2.1.2         | pypi_0         | pypi          |
| matplotlib                | 3.7.1         | pypi_0         | pypi          |
| mmcv-full                 | 1.6.2         | pypi_0         | pypi          |
| mpmath                    | 1.2.1         | pypi_0         | pypi          |
| networkx                  | 3.0           | pypi_0         | pypi          |
| ninja                     | 1.11.1        | pypi_0         | pypi          |
| numpy                     | 1.23.3        | pypi_0         | pypi          |
| opencv-python             | 4.6.0.66      | pypi_0         | pypi          |
| openssl                   | 3.1.2         | hcfcfb64_0     | conda-forge   |
| packaging                 | 23.1          | pypi_0         | pypi          |
| pillow                    | 9.2.0         | pypi_0         | pypi          |
| pip                       | 23.2.1        | pyhd8ed1ab_0   | conda-forge   |
| platformdirs              | 3.10.0        | pypi_0         | pypi          |
| plotly                    | 5.10.0        | pypi_0         | pypi          |
| pycocotools               | 2.0.5         | pypi_0         | pypi          |
| pyparsing                 | 3.0.9         | pypi_0         | pypi          |
| python                    | 3.10.12       | h4de0772_0_cpython | conda-forge |
| python-dateutil           | 2.8.2         | pypi_0         | pypi          |
| pywavelets                | 1.4.1         | pypi_0         | pypi          |
| pyyaml                    | 6.0           | pypi_0         | pypi          |
| regex                     | 2023.8.8      | pypi_0         | pypi          |
| requests                  | 2.28.1        | pypi_0         | pypi          |
| scikit-image              | 0.19.3        | pypi_0         | pypi          |
| scipy                     | 1.10.0        | pypi_0         | pypi          |
| segment-anything          | 1.0           | dev_0          | <develop>     |
| setuptools                | 63.4.1        | pypi_0         | pypi          |
| six                       | 1.16.0        | pypi_0         | pypi          |
| supervision               | 0.6.0         | pypi_0         | pypi          |
| sympy                     | 1.11.1        | pypi_0         | pypi          |
| tenacity                  | 8.2.3         | pypi_0         | pypi          |
| tifffile                  | 2023.8.12     | pypi_0         | pypi          |
| timm                      | 0.6.13        | pypi_0         | pypi          |
| tk                        | 8.6.12        | h8ffe710_0     | conda-forge   |
| tokenizers                | 0.13.3        | pypi_0         | pypi          |
| tomli                     | 2.0.1         | pypi_0         | pypi          |
| torch                     | 1.12.1+cu116  | pypi_0         | pypi          |
| torch-efficient-distloss  | 0.1.3         | pypi_0         | pypi          |
| torch-scatter             | 2.0.9         | pypi_0         | pypi          |
| torchaudio                | 0.12.1+cu116  | pypi_0         | pypi          |
| torchvision               | 0.13.1+cu116  | pypi_0         | pypi          |
| tqdm                      | 4.64.1        | pypi_0         | pypi          |
| transformers              | 4.29.1        | pypi_0         | pypi          |
| typing-extensions         | 4.4.0         | pypi_0         | pypi          |
| tzdata                    | 2023c         | h71feb2d_0     | conda-forge   |
| ucrt                      | 10.0.22621.0  | h57928b3_0     | conda-forge   |
| urllib3                   | 1.26.13       | pypi_0         | pypi          |
| vc                        | 14.3          | h64f974e_17    | conda-forge   |
| vc14_runtime              | 14.36.32532   | hfdfe4a8_17    | conda-forge   |
| vs2015_runtime            | 14.36.32532   | h05e6639_17    | conda-forge   |
| werkzeug                  | 2.3.7         | pypi_0         | pypi          |
| wheel                     | 0.41.1        | pyhd8ed1ab_0   | conda-forge   |
| xz                        | 5.2.6         | h8d14728_0     | conda-forge   |
| yapf                      | 0.32.0        | pypi_0         | pypi          |
| zipp                      | 3.16.2        | pypi_0         | pypi          |

My CUDA version: 11.6 (originally I had 12.0, but I had to downgrade to 11.6 to match the torch version for this project)

Any solution?

**Comment by Jumpat** [comment]
Thanks for your interests! We never encounter with such problem in practice.  I think this may caused by the version mismatch of torch_scatter (maybe mismatch with the device environment). Please try to re-install the torch_scatter with another version following the instruction on its [github page](https://github.com/rusty1s/pytorch_scatter) and check whether it helps.

**Comment by Jumpat** [comment]
> error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]" 

I guess this is also caused by some version mismatch problem (nvcc, cuda toolkit, cudnn, g++,  ...). We didn't test sa3d on windows platform previously.

cat /proc/version shows: Linux version 5.15.0-76-generic (buildd@lcy02-amd64-019) (gcc (Ubuntu 9.4.0-1ubuntu1\~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #83~20.04.1-Ubuntu SMP

I hope the attached [packages.txt](https://github.com/Jumpat/SegmentAnythingin3D/files/12360291/packages.txt) can help you find some solution.

**Comment by faisalahmedsifat** [comment]
I am also facing same problem in my Ubuntu 23.04, There's some version mismatch problem. Is it possible to share a docker image?

**Comment by Zanue** [comment]
Our code is based on [DVGO](https://github.com/sunset1995/DirectVoxGO) and we have not met this problem. You can try to search for solutions in DVGO issues. I also find a related issue [here](https://github.com/pytorch/pytorch/issues/32694) and hope it can help you.

We will release the nerfstudio implementation of  `sa3d` as soon as possible, which will not have these problems. Sorry for the inconvenience.
