### ISSUE TITLE
About the results on Replica dataset

### ISSUE THREAD

**Issue by zhongyingji** [Jumpat/SegmentAnythingin3D#27]
Thanks for the great work!

I noticed that only mipnerf360, LLFF, LERF datasets are available. Will the Replica dataset be available? 

BTW, I noticed that there is a load_replica.py file, is the data processing code of this file usable?

**Comment by Zanue** [comment]
Hi! The `load_replica.py` file is usable. We use the [pre-rendered Replica data](https://github.com/Harry-Zhi/semantic_nerf#we-also-provide-pre-rendered-replica-data-that-can-be-directly-used-by-semantic-nerf) in the SemanticNeRF repo. You can easily construct the configs of Replica following the configs of other unbounded datasets. Note that the camera poses in the Replica dataset use the OpenCV format, thus you need to set `inverse_y=True` in your Replica configs.

**Comment by zhongyingji** [comment]
Thanks for the reply. 

What do you mean by unbounded datasets? I checked the load_data.py file, all datasets except for mipnerf360 call the function `inward_nearfar_heuristic ` which returns near/far bound. Does it mean that only mipnerf360 dataset is treated as unbounded datasets? 

Thank you: )

**Comment by Zanue** [comment]
By saying 'unbounded datasets' we mean the datasets with more than forward-facing views, such as `mipnerf360` and `LERF` datasets. Forward-facing scenes and unbounded scenes are trained with different types of NeRFs. In [line 194-201](https://github.com/Jumpat/SegmentAnythingin3D/blob/38f82e2778bfe9336c9af5b7f5b6835a64187b6e/lib/utils.py#L194) of `lib/utils.py`, when the scene is forward-facing, its config will set `ndc=True` and `unbounded_inward=False`, then the DVGO model is chosen. When the scene is unbounded, its config will set `ndc=False` and `unbounded_inward=True`, then the DCVGO model is chosen.

**Comment by zhongyingji** [comment]
Ok, I see. I will check the code and reopen the issue if I have further questions. : )
Thank you.

**Comment by zhongyingji** [comment]
> 

So you mean for Replica dataset, you treat it as unbounded scene and choose `dcvgo.DirectContractedVoxGO` model.
Why do you treat it as an unbounded scene? 
Is it a big problem if I build a vanilla NeRF on it treating it as a bounded scene with the near/far bound get from the `inward_nearfar_heuristic` function?

**Comment by Zanue** [comment]
> Is it a big problem if I build a vanilla NeRF on it treating it as a bounded scene with the near/far bound get from the inward_nearfar_heuristic function?

Of course you can try it. The reason we choose DCVGO rather than DVGO is that, DCVGO has a *contract(·)* operator which is from mipnerf 360. This can help improve the novel view rendering quality in Replica scenes.
