### ISSUE TITLE
how to segment everything and generate segmentation for Multi-objects

### ISSUE THREAD

**Issue by mohit-av** [Jumpat/SegmentAnythingin3D#28]
It's a really great approach created by you guys to create the 3D segments. I run it on few objects and it's giving really good segmentation. But I have few questions:

How can I do the parts segmentation of the object. Let's take an example of horns, I want both horn to be as different masks. i.e segmenting as multi-objects. 
I tried to use `--segment everything` flag in this way:
```
python run_seg_gui.py --config=configs/llff/seg/seg_horns.py --segment_everything --sp_name=_gui --num_prompts=20 --render_opt=train --save_ckpt
```
So, that I can create different mask for each part of the object. But it resulted in loading the same old `gui`. Any suggestion how can I do it?

Any help would be really appreciable.

**Comment by Jumpat** [comment]
Hello! Thanks for your interest! 
I'm sorry to say that the current code cannot support the multi-object segmentation mode now. To get part of the object, you can simply segment it as the whole object (that is, input prompt, select mask and run). 
The segment_everything flag is temporarily unused, which, in fact, is equivalent to segment the expected part one by one (so we abandon it in the code refactoring, its previous code is really very dirty).
Hope this can help you!

**Comment by Jumpat** [comment]
> So, in theory, could this pipeline segment different objects (like the laptop and the food at the table) at once?
> 
> Thank you very much!!

Hi. So sorry for this late response. I missed this issue. You're right. SA3D can segment multiple things In theory, which is equivalent conduct several segmentation in parallel.
