### ISSUE TITLE
What is the code directory structure like？

### ISSUE THREAD

**Issue by ydi-mua** [Jumpat/SegmentAnythingin3D#29]
![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/47213f30-d20d-4ca8-907d-5569edf5e21d)

![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/f6d8d778-598a-49ac-9c7d-ebf189b83a92)
![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/3beb5f6d-3359-4eed-91dd-62be3f4527b5)
![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/8500f616-4160-4284-a9f8-60b9613a5ed6)

Is this right？

**Comment by Jumpat** [comment]
Yes, I think this is ok. If there is any other problem please let me know.

**Comment by ydi-mua** [comment]
> Yes, I think this is ok. If there is any other problem please let me know.

![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/75960aa8-d1c0-4ff6-ab3d-c5b74cd8d397)

**Comment by Jumpat** [comment]
This seems a little weird. 
If the SAM is **correctly installed**, this may be caused by a bug in [lib/sam3d.py](https://github.com/Jumpat/SegmentAnythingin3D/blob/8d246f610129cd630bd1e5bf1be6c7e0f47abb0f/lib/sam3d.py#L29C1-L40C1). Remove these lines about the MobileSAM may solve this.

**Comment by ydi-mua** [comment]
> This seems a little weird. If the SAM is **correctly installed**, this may be caused by a bug in [lib/sam3d.py](https://github.com/Jumpat/SegmentAnythingin3D/blob/8d246f610129cd630bd1e5bf1be6c7e0f47abb0f/lib/sam3d.py#L29C1-L40C1). Removing these lines about the MobileSAM may solve this.

I moved segment-anything to dependencies/sam_ckpt,can solve the problem of module not being found， like this:
![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/54953d17-c55f-492c-9f30-a748216222ee)
 but other problems that aris，
 
![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/46986309-0e89-4c64-8393-d0ccdf6078ac)

**Comment by ydi-mua** [comment]
![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/3299becb-0724-474c-bea9-e5e1bcaf8a12)

**Comment by Jumpat** [comment]
Yeah, this is the problem of MobileSAM, removing the "if args.mobile_sam" and directly use sam can help.

**Comment by ydi-mua** [comment]
> Yeah, this is the problem of MobileSAM, removing the "if args.mobile_sam" and directly use sam can help.

removed it ,There are other issues that have arisen again,
![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/46c00aa1-b2e0-4022-acb2-85ba241bd0b1)

**Comment by ydi-mua** [comment]
Thank you for your reply. it succeeded!
![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/4aa6fc8f-c184-4b84-993d-92f74fba11e2)

**Comment by Jumpat** [comment]
You are welcome~ Let me know if there is any other problem.

**Comment by ydi-mua** [comment]
> > Yeah, this is the problem of MobileSAM, removing the "if args.mobile_sam" and directly use sam can help.
> 
> Can you show the code after removing the "if args.mobile_sam"?

![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/105626420/392f4788-90b8-4944-bc32-e71dd800841c)

**Comment by ydi-mua** [comment]
> How to solve this error? I also encountered this error. ![image](https://user-images.githubusercontent.com/33644565/279698288-bebcbc31-76f7-44c1-baf5-2f58833028de.png)

Reinstall dash
