### ISSUE TITLE
Explanation Needed on `dual_seg_mask_grid` Usage in Fine Stage

### ISSUE THREAD

**Issue by longxinglx** [Jumpat/SegmentAnythingin3D#31]
Hello,

While going through the code in `seg_dvgo.py`, I've noticed the usage of `dual_seg_mask_grid` in line 70. From my observation, the parameters and training process of `dual_seg_mask_grid` appear identical to `seg_mask_grid`. And, `dual_seg_mask_grid` seems to be used only when calculating loss in the fine stage. In the fine stage, the loss is computed for both `seg_mask_grid` and `dual_seg_mask_grid` in the same manner, and the output loss is the sum of these two losses.

Could you provide some clarity on the rationale behind introducing an additional `dual_seg_mask_grid` during the fine stage? Is there a specific reason or advantage to this approach?

Thank you for your time, and I look forward to your clarification.

**Comment by Jumpat** [comment]
Thanks for your interest! In the section A.2 of our [paper](https://arxiv.org/pdf/2304.12308.pdf), we introduced the dual segmentation mechanism (also named as two-pass segmentation). In the current code we do not ensure the dual segmentation can work normally (the code has been refactored). 
The insight behind the dual segmentation is using another mask grids to maintain the incorrectly segmented parts of the first coarse segmentation stage. The generated self-prompting points for the dual_seg_mask_grid are used as negative points for the seg_mask_grid and vice versa. This mechanism can utilize the negative prompts of SAM to further improve the segmentation performance.
However, we found that generally the performance of the first stage is good enough. Thus we omit this trick in our main paper.

**Comment by longxinglx** [comment]
> Thanks for your interest! In the section A.2 of our [paper](https://arxiv.org/pdf/2304.12308.pdf), we introduced the dual segmentation mechanism (also named as two-pass segmentation). In the current code we do not ensure the dual segmentation can work normally (the code has been refactored). The insight behind the dual segmentation is using another mask grids to maintain the incorrectly segmented parts of the first coarse segmentation stage. **The generated self-prompting points for the dual_seg_mask_grid are used as negative points for the seg_mask_grid and vice versa.** This mechanism can utilize the negative prompts of SAM to further improve the segmentation performance. However, we found that generally the performance of the first stage is good enough. Thus we omit this trick in our main paper.

Thank you for the detailed explanation!
