### ISSUE TITLE
Application of this work

### ISSUE THREAD

**Issue by ukaukaaaa** [Jumpat/SegmentAnythingin3D#32]
Hi,

Thanks for this great work. 

I have one question. What do you think is the best application of this study? Since it still requires human prompt input, I was curious about its advantage over other fully automatic 3D representation models.

**Comment by Jumpat** [comment]
Thanks for your interest! 
Just like SAM itself, though SA3D requires prompts for segmentation, the prompt can be generated automatically in fact, which may help some other downstream tasks.
Moreover, I think an intuitive application is auto-labelling. With this framework one can easily annotate multi-view images.

**Comment by ukaukaaaa** [comment]
Thanks for your reply.
What do you mean automatically generate the prompt. In which way?

**Comment by ukaukaaaa** [comment]
> Thanks for your interest!
> Just like SAM itself, though SA3D requires prompts for segmentation, the prompt can be generated automatically in fact, which may help some other downstream tasks.
> Moreover, I think an intuitive application is auto-labelling. With this framework one can easily annotate multi-view images.

Thanks for your reply.
What do you mean automatically generate the prompt. In which way?

**Comment by Jumpat** [comment]
This depends on the concrete scene. For example, SA3D can be combined with vision-language model like CLIP / GPT to realize instruction-based fine-grained 3D segmentation.
