### ISSUE TITLE
sam raw images directly

### ISSUE THREAD

**Issue by D6561** [Jumpat/SegmentAnythingin3D#33]
Thanks for your great jobs!
When I run run_seg_gui.py to get the masks,I found that the the images are rendered after nerf.And --render_opt=train also just get the rendered images with the same camera poses of raw images, but I want to get the masks of raw images.So i wonder does this project provide the function that could sam the raw images directly？

**Comment by Jumpat** [comment]
The segmentation of SA3D requires the 3D structure information embedded in the NeRF. Consequently, it is different from directly segmenting the original images. But I think if the rendering quality of the NeRF is good, simply upsampling the mask to the resolution of the raw images can meet your requirement.

**Comment by D6561** [comment]
Yes, i find it heavily depend on the quality of rendering pictures and I tried some other dataset like toydesk1 and scannet0113,the quality of nerf is poor ,so it always shows "No prompt is available" after the first picture.

**Comment by Jumpat** [comment]
Yeah, The target of SA3D is to segment a well-trained NeRF model. 
However, if the quality of the 3D reconstruction is poor, SA3D cannot achieve good performance (SA3D cannot affect the geometry of the original model).
