### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Lizhinwafu** [Jumpat/SegmentAnythingin3D#35]
According to the code given, I cannot configure it successfully. I would like to ask if anyone has successfully configured it?

**Comment by Zanue** [comment]
Can you provide more details? For example, in the installation process where  did the error occur?

**Comment by Zanue** [comment]
The error seems to be that you have not installed SAM following [this](https://github.com/Jumpat/SegmentAnythingin3D#sam-and-grounding-dino).

**Comment by Zanue** [comment]
In your environment, was this [line](https://github.com/Jumpat/SegmentAnythingin3D/blob/8d246f610129cd630bd1e5bf1be6c7e0f47abb0f/lib/sam3d.py#L12) successfully conducted? You can try `from segment_anything import sam_model_registry` to check if your SAM are installed successfully.

**Comment by Zanue** [comment]
Please refer to this [issue](https://github.com/Jumpat/SegmentAnythingin3D/issues/29#issuecomment-1752611520). It seems to be the problem of MobileSAM.
