### ISSUE TITLE
How much memory is required to train SA3D, and how to make own dataset?

### ISSUE THREAD

**Issue by Lizhinwafu** [Jumpat/SegmentAnythingin3D#36]
How much memory is required to train SA3D, and how to make own dataset?

**Comment by Jumpat** [comment]
The GPU memory cost depends on the scene. A 24GB (e.g., RTX3090) GPU is usually enough. For training on custom dataset, you may find some help from [DirectVoxGo](https://github.com/sunset1995/DirectVoxGO/tree/main). You need to process the data with COLMAP and put it under the specific data structure.

**Comment by Zanue** [comment]
(1) To use low resolution images for training, you need to firstly ensure that in your data directory there are folders like [images|images_2|images_4|images_8]. This can be created by COLMAP. Then you need to specify the `factor` parameter in your configs, like [this](https://github.com/Jumpat/SegmentAnythingin3D/blob/f22315ea50c3d1d000f4601e508d2af47b0171be/configs/nerf_unbounded/bicycle.py#L7C7-L7C7). `factor` means the downsample factor of training images. 

(2) 
> Maybe it needs to be made into LERF format or mip-NeRF360.

This is right. `LLFF` scenes are forward-facing, while `LERF` and `mip-NeRF360` scenes are 360°. Therefore, the `LLFF` format data are trained with `DVGO` with ndc processing, and `LERF` and `mip-NeRF360` data are trained with `DCVGO` without ndc.

(3) We have not published this part of code yet. It can be implemented by setting the class of `seg_mask_grid` to be n+1(n is the object number and 1 represents the unknown class), and modifying the training process and loss function of the code correspondingly. 

(4) 
> Another question, should these two places in the nerf_unbounded data set be the same?

Yes, they should be.
