### ISSUE TITLE
How to choose the perspective so that the rendered lerf video is the same as llff (such as surrounding a target). ​

### ISSUE THREAD

**Issue by Lizhinwafu** [Jumpat/SegmentAnythingin3D#39]
How to choose the perspective so that the rendered lerf video is the same as llff (such as surrounding a target).
​

**Comment by Zanue** [comment]
You can use [`--render_opt`](https://github.com/Jumpat/SegmentAnythingin3D/blob/d7b3dc3f0f8b5e2cb8c84c8573b270a36176c01c/lib/configs.py#L26C33-L26C33) to specify the pose sequence used for the rendered video. `train` means the training sequence, and `video` means the fly-through sequence.

**Comment by Jumpat** [comment]
Hello! Thanks for your interest! If you are using your own dataset you have to generate the camera path (a set of camera poses) by yourself. You can check the dataloader in ./lib for some help (especially the load_lerf.py, load_llff.py, ...).

**Comment by Jumpat** [comment]
We use tensorf as the nerf model.
