### ISSUE TITLE
mmcv环境配置问题

### ISSUE THREAD

**Issue by Joeyicheng** [Jumpat/SegmentAnythingin3D#4]
请问是如何配置mmcv呢，我在官网上没有看到支持torch1.12.1的版本，我是用pip install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12.1/index.html下载的，会报错，我的cuda是11.3，显卡是RTX 3090，可以告诉我详细的环境或步骤吗？
######
Please tell me how to configure mmcv, I don't see support for torch 1.12.1 on the official website, I am using pip install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12.1/ index.html download, will report an error, my cuda is 11.3, can you tell me the details of the environment or steps

**Comment by Joeyicheng** [comment]
I try to pip install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html,and it will be OK.

**Comment by Jumpat** [comment]
😺👍
