### ISSUE TITLE
tensorf是一个预训练模型吗，是不是说可以不运行run.py，直接用预训练模型运行run_seg_gui.py就行呢

### ISSUE THREAD

**Issue by ilovebing** [Jumpat/SegmentAnythingin3D#46]
我看您的论文里，有说您使用的tensorf预训练模型，这个有链接吗，是通用的预训练模型吗，我理解是不是只要用这个通用预训练模型，就可以直接进行自己数据集的裁切和3D重建了呢？
期待您的回复，谢谢

**Comment by ilovebing** [comment]
我是一个没有怎么做过nerf的小白，只是跑过几个开源项目，像instant-ngp，neuralange等，对于nerf的原理也大概清楚，想看看您这有没有什么建议或者资料，能让我非常熟悉您的论文和代码。您的论文我读过了，里面的掩码逆渲染和交叉视图自提示我觉得我理解了。现在在看您的代码，但是感觉有点吃力

**Comment by Jumpat** [comment]
你好！tensorf（可以理解为一种nerf）是一种三维表征，预训练过程指的就是根据输入的二维多视角图像构成三维模型的过程，因此并不能够“只要用这个通用预训练模型，就可以直接进行自己数据集的裁切和3D重建”，而是需要先准备好自己的数据集，进而使用这个数据集（预）训练一个tensorf模型。

**Comment by ilovebing** [comment]
明白了，谢谢
