### ISSUE TITLE
How to run metashape xml files on sa3d？

### ISSUE THREAD

**Issue by tbw831** [Jumpat/SegmentAnythingin3D#48]
Hi, Thanks for your work!

Now I want to run a mask on sa3d with some data calibrated by metashape, which data format should I convert to? The coordinate system of various data formats is different, I am confused about this, can you help me?

**Comment by Jumpat** [comment]
Hello! SA3D is based on NeRF. You need to get the multi-view images for the scene and the corresponding camera poses and then train a nerf first!
