### ISSUE TITLE
Export 2D masks for SA3D's rendered images

### ISSUE THREAD

**Issue by peterjohnsonhuang** [Jumpat/SegmentAnythingin3D#49]
Hi,
Congrats for the great work!
I want to know if you provide an easy way to get all the 2D binary mask for the final results after applying your SA3D. For example, I tried the "Fern" case and I found .mp4 videos of rendered images and masks in the log directory. So does your code provide any part that I can output .png files of RGB image and binary mask for the 16 views or I should just take the .mp4 file and take out each frame by myself?
Thanks again!

**Comment by Jumpat** [comment]
Hello, thanks for your interest!

You can check and modify the [./lib/render_utils.py](https://github.com/Jumpat/SegmentAnythingin3D/blob/main/lib/render_utils.py) package to save the original masks.

**Comment by peterjohnsonhuang** [comment]
Thank you so much!

I should close this issue now 😂
