### ISSUE TITLE
Nerfstudio version

### ISSUE THREAD

**Issue by lai888123321** [Jumpat/SegmentAnythingin3D#50]
Thank you for your great work. 

I have several questions regarding your project:

1. Is there any way to use nerfstudio to render 2D mask based on training images accordingly?
2. From my result shown in the uploaded video, I ask the model to segment the "conference table" based on the "room" LLFF dataset, but the segmentation result of some views are not good, is there any reason causing it?

https://github.com/Jumpat/SegmentAnythingin3D/assets/75596632/dcd68c8f-9e95-4518-b63d-3c4bb8a10fbf

**Comment by Zanue** [comment]
1. We have not tried to save the rendered masks in nerfstudio, but I think it can be done by using `ns-render --rendered-output-names=mask_scores` (refer to [this link](https://docs.nerf.studio/quickstart/first_nerf.html#exporting-results)).
2. In our sa3d-nerfstudio, we use hash grids to be mask grids.  Therefore, you can try to increase the `log2_hashmap_size`, or decrease the `mask_threshold` [here](https://github.com/Jumpat/SegmentAnythingin3D/blob/8bde6dc59b15b8369e814f672d021bdefb1ca463/sa3d/sa3d_config.py#L54).
