### ISSUE TITLE
Failed to build Grounding-Dino

### ISSUE THREAD

**Issue by 2085924055** [Jumpat/SegmentAnythingin3D#53]
Run the pip install -e .
The following problems occur.
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Obtaining file:///G:/SegmentAnythingin3D/GroundingDINO
Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from groundingdino==0.1.0) (1.12.1)
Requirement already satisfied: torchvision in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from groundingdino==0.1.0) (0.13.1)
Requirement already satisfied: transformers in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from groundingdino==0.1.0) (4.29.1)
Requirement already satisfied: addict in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from groundingdino==0.1.0) (2.4.0)
Requirement already satisfied: yapf in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from groundingdino==0.1.0) (0.32.0)
Requirement already satisfied: timm in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from groundingdino==0.1.0) (0.6.13)
Requirement already satisfied: numpy in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from groundingdino==0.1.0) (1.26.3)
Requirement already satisfied: opencv-python in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from groundingdino==0.1.0) (4.6.0.66)
Requirement already satisfied: supervision in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from groundingdino==0.1.0) (0.6.0)
Requirement already satisfied: pycocotools in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from groundingdino==0.1.0) (2.0.5)
Requirement already satisfied: matplotlib>=2.1.0 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from pycocotools->groundingdino==0.1.0) (3.8.2)
Requirement already satisfied: pyyaml in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from timm->groundingdino==0.1.0) (6.0)
Requirement already satisfied: huggingface-hub in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from timm->groundingdino==0.1.0) (0.14.1)
Requirement already satisfied: typing_extensions in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from torch->groundingdino==0.1.0) (4.9.0)
Requirement already satisfied: requests in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from torchvision->groundingdino==0.1.0) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from torchvision->groundingdino==0.1.0) (9.2.0)
Requirement already satisfied: filelock in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from transformers->groundingdino==0.1.0) (3.13.1)
Requirement already satisfied: packaging>=20.0 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from transformers->groundingdino==0.1.0) (23.2)
Requirement already satisfied: regex!=2019.12.17 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from transformers->groundingdino==0.1.0) (2023.12.25)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from transformers->groundingdino==0.1.0) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from transformers->groundingdino==0.1.0) (4.64.1)
Requirement already satisfied: fsspec in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from huggingface-hub->timm->groundingdino==0.1.0) (2023.12.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (1.2.0)
Requirement already satisfied: cycler>=0.10 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (4.47.0
)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (2.8
.2)
Requirement already satisfied: colorama in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from tqdm>=4.27->transformers->groundingdino==0.1.0) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (2023.11.17)
Requirement already satisfied: six>=1.5 in d:\anaconda3\envs\segmentanythingin3d\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.1.0->pycocotools->groundingdino==0
.1.0) (1.16.0)
Installing collected packages: groundingdino
Running setup.py develop for groundingdino
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [48 lines of output]
    Building wheel groundingdino-0.1.0
    Compiling with CUDA
    running develop
    D:\Anaconda3\envs\SegmentAnythingin3D\lib\site-packages\setuptools\command\develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
   
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
   
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
   
    !!
      easy_install.initialize_options(self)
    D:\Anaconda3\envs\SegmentAnythingin3D\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
   
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
   
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
   
    !!
      self.initialize_options()
    running egg_info
    writing groundingdino.egg-info\PKG-INFO
    writing dependency_links to groundingdino.egg-info\dependency_links.txt
    writing requirements to groundingdino.egg-info\requires.txt
    writing top-level names to groundingdino.egg-info\top_level.txt
    reading manifest file 'groundingdino.egg-info\SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'groundingdino.egg-info\SOURCES.txt'
    running build_ext
    D:\Anaconda3\envs\SegmentAnythingin3D\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: The detected CUDA version (11.6) has a minor version mismatch wi
th the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'groundingdino._C' extension
Emitting ninja build file G:\SegmentAnythingin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /M
ANIFESTUAC:NO /LIBPATH:D:\Anaconda3\envs\SegmentAnythingin3D\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\lib/x64" /LIBPATH:D
:\Anaconda3\envs\SegmentAnythingin3D\libs /LIBPATH:D:\Anaconda3\envs\SegmentAnythingin3D /LIBPATH:D:\Anaconda3\envs\SegmentAnythingin3D\PCbuild\amd64 "/LIBPATH:C:\Program File
s\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130
lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.
22621.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit__C G:\SegmentAnythingin3D\Groundi
ngDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\groundingdino\models\GroundingDINO\csrc\MsDeformAttn\ms_deform_attn_cpu.obj G:\SegmentAnythin
gin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\groundingdino\models\GroundingDINO\csrc\MsDeformAttn\ms_deform_attn_cuda.obj G:
SegmentAnythingin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\groundingdino\models\GroundingDINO\csrc\cuda_version.obj G:\Segmen
tAnythingin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\groundingdino\models\GroundingDINO\csrc\vision.obj /OUT:build\lib.win-am
d64-cpython-310\groundingdino_C.cp310-win_amd64.pyd /IMPLIB:G:\SegmentAnythingin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\gr
oundingdino\models\GroundingDINO\csrc\MsDeformAttn_C.cp310-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“G:\SegmentAnythingin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\groundingd
ino\models\GroundingDINO\csrc\MsDeformAttn\ms_deform_attn_cpu.obj”
error: command 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\link.exe' failed with exit code 1181
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [48 lines of output]
Building wheel groundingdino-0.1.0
Compiling with CUDA
running develop
D:\Anaconda3\envs\SegmentAnythingin3D\lib\site-packages\setuptools\command\develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
D:\Anaconda3\envs\SegmentAnythingin3D\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing groundingdino.egg-info\PKG-INFO
writing dependency_links to groundingdino.egg-info\dependency_links.txt
writing requirements to groundingdino.egg-info\requires.txt
writing top-level names to groundingdino.egg-info\top_level.txt
reading manifest file 'groundingdino.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'groundingdino.egg-info\SOURCES.txt'
running build_ext
D:\Anaconda3\envs\SegmentAnythingin3D\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: The detected CUDA version (11.6) has a minor version mismatch with t
he version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'groundingdino._C' extension
Emitting ninja build file G:\SegmentAnythingin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIF
ESTUAC:NO /LIBPATH:D:\Anaconda3\envs\SegmentAnythingin3D\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\lib/x64" /LIBPATH:D:\An
aconda3\envs\SegmentAnythingin3D\libs /LIBPATH:D:\Anaconda3\envs\SegmentAnythingin3D /LIBPATH:D:\Anaconda3\envs\SegmentAnythingin3D\PCbuild\amd64 "/LIBPATH:C:\Program Files\Mi
crosoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\lib
x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.2262
1.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit__C G:\SegmentAnythingin3D\GroundingDI
NO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\groundingdino\models\GroundingDINO\csrc\MsDeformAttn\ms_deform_attn_cpu.obj G:\SegmentAnythingin3
D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\groundingdino\models\GroundingDINO\csrc\MsDeformAttn\ms_deform_attn_cuda.obj G:\Segm
entAnythingin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\groundingdino\models\GroundingDINO\csrc\cuda_version.obj G:\SegmentAny
thingin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\groundingdino\models\GroundingDINO\csrc\vision.obj /OUT:build\lib.win-amd64-
cpython-310\groundingdino_C.cp310-win_amd64.pyd /IMPLIB:G:\SegmentAnythingin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\ground
ingdino\models\GroundingDINO\csrc\MsDeformAttn_C.cp310-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“G:\SegmentAnythingin3D\GroundingDINO\build\temp.win-amd64-cpython-310\Release\SegmentAnythingin3D\GroundingDINO\groundingdino
models\GroundingDINO\csrc\MsDeformAttn\ms_deform_attn_cpu.obj”
error: command 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\link.exe' failed with exit code 1181
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

I use windows system, the environment is as follows

Name Version 
addict==2.4.0
blas==1.0 
blas-devel==3.9.0 
blinker==1.7.0 
brotli-python==1.0.9 
bzip2==1.0.8 
ca-certificates==2023.12.12 
certifi==2023.11.17 
charset-normalizer==3.3.2 
click==8.1.7 
colorama==0.4.6 
contourpy==1.2.0 
cudatoolkit==11.3.1 
cycler==0.12.1 
dash==2.6.2 
dash-core-components==2.0.0 
dash-html-components==2.0.0 
dash-table==5.0.0 
filelock==3.13.1 
flask==3.0.0 
flask-compress==1.14 
fonttools==4.47.0 
freetype==2.10.4 
fsspec==2023.12.2 
huggingface-hub==0.14.1 
idna==3.6 
imageio==2.22.2 
intel-openmp==2023.2.0 
itsdangerous==2.1.2 
jinja2==3.1.2 
jpeg==9e 
kiwisolver==1.4.5 
libblas==3.9.0 
libcblas==3.9.0 
libffi==3.4.4 
liblapack==3.9.0 
liblapacke==3.9.0 
libpng==1.6.37 
libtiff==4.0.9 
libuv==1.44.2
libwebp==1.2.4 
libwebp-base==1.2.4 
lpips==0.1.4 
m2w64-gcc-libgfortran==5.3.0 
m2w64-gcc-libs==5.3.0 
m2w64-gcc-libs-core==5.3.0 
m2w64-gmp==6.1.0 
m2w64-libwinpthread-git==5.0.0.4634.697f757 
markupsafe==2.1.3 
matplotlib==3.8.2 
mkl==2023.2.0 
mkl-devel==2023.2.0 
mkl-include==2023.2.0 
mkl-service==2.4.0 
mkl_fft==1.3.8 
mkl_random==1.2.4 
msys2-conda-epoch  20160418
networkx==3.2.1 
numpy==1.26.3 
numpy-base==1.26.3 
opencv-python==4.6.0.66
openssl==3.0.12 
packaging==23.2 
pillow==9.2.0 
pip==23.3.1
plotly==5.10.0 
pycocotools==2.0.5 
pyparsing==3.1.1 
pysocks==1.7.1 
python==3.10.13 
python-dateutil==2.8.2 
python_abi==3.10 
pytorch==1.12.1 
pytorch-mutex==1.0 
pywavelets==1.5.0 
pyyaml==6.0 
regex==2023.12.25 
requests==2.31.0 
scikit-image==0.19.3 
scipy==1.10.0 
segment-anything==1.0 
setuptools==63.4.1 
six==1.16.0 
sqlite==3.41.2 
supervision==0.6.0 
tbb==2021.5.0 
tenacity==8.2.3 
tifffile==2023.12.9 
timm==0.6.13 
tk==8.6.12 
tokenizers==0.13.3 
torch-efficient-distloss==0.1.3 
torch-scatter==2.0.9 
torchaudio==0.12.1 
torchvision==0.13.1 
tqdm==4.64.1 
transformers==4.29.1 
typing_extensions==4.9.0 
tzdata  2023d 
urllib3==2.1.0 
vc==14.2 
vs2015_runtime  14.27.29016 
werkzeug==3.0.1 
wheel==0.41.2 
win_inet_pton==1.1.0 
xz==5.4.5 
yapf==0.32.0 
zlib==1.2.13 

Does anyone have this problem? How to solve this problem?

**Comment by Jumpat** [comment]
Hello
Very sorry for the late reply. This issue seems to be a link library error. Our code has not been test on the windows platform before. Maybe you can refer to the repo of [GroundingDINO](https://github.com/IDEA-Research/GroundingDINO) for some help.
