### ISSUE TITLE
Runtime Error on MipNeRF-360 dataset

### ISSUE THREAD

**Issue by ankitatiisc** [Jumpat/SegmentAnythingin3D#54]
When I run the following commond : 
`python run_seg_gui.py --config=configs/nerf_unbounded/seg_garden.py --segment --sp_name=_gui --num_prompts=20 --render_opt=train --save_ckpt`

I get this error : 
`AttributeError: 'Flask' object has no attribute 'before_first_request'. Did you mean: '_got_first_request'?`

Did anyone face this issue ?

**Comment by Jumpat** [comment]
Hi, this seems to be the version error of flask. We use flask=2.2.5 in practice. 

Please try 
>pip install flask==2.2.5 --force-reinstall
