### ISSUE TITLE
Trouble with running SA3D with GUI

### ISSUE THREAD

**Issue by dsumigar** [Jumpat/SegmentAnythingin3D#55]
I am trying to run SA3D with GUI. I have completed the installation and finished training NeRF. However, when I run the command to run with GUI :
```
python run_seg_gui.py --config=configs/llff/seg/seg_fern.py --segment --sp_name=_gui --num_prompts=20 --render_opt=train --save_ckpt
```
I am able to begin the training before I start getting this error in the sam3d.py file:
```
self.sam = sam_model_registry[model_type](checkpoint=sam_checkpoint).to(device)
UnboundLocalError: local variable 'sam_model_registry' referenced before assignment
```

Has anyone come across this issue? I have double-checked with the installation process and I'm sure I have completed every step.

Thanks.

**Comment by Jumpat** [comment]
Hello, this is caused by the integration of MobileSAM. Please refer to [this issue](https://github.com/Jumpat/SegmentAnythingin3D/issues/29#issuecomment-1752539370) for more information.
