### ISSUE TITLE
How to obtain the 3D point cloud after segmenting?

### ISSUE THREAD

**Issue by Lizhinwafu** [Jumpat/SegmentAnythingin3D#56]
How to obtain the 3D point cloud after segmenting?

**Comment by Jumpat** [comment]
Hello! I'm sorry but SA3D does not support transferring NeRF to point cloud currently.

**Comment by Jumpat** [comment]
Please provide more information about the scene (or dataset) you are testing on. Please first check whether the NeRF runs well on the data. We need more information for diagnosing the problem.

**Comment by Zanue** [comment]
Can you provide your python script in the second stage?

**Comment by Zanue** [comment]
SJTU19zzw@sjtu.edu.cn
