### ISSUE TITLE
License details for commercial use

### ISSUE THREAD

**Issue by archana-ramalingam** [Jumpat/SegmentAnythingin3D#58]
Thanks for open sourcing this amazing work!

The SAM and DINO model licenses allow commercial use. Could you please confirm if your Sa3D code is licensed for commercial use too?

**Comment by archana-ramalingam** [comment]
Hello, bumping up this issue. Please let me know if you have an update.

**Comment by Jumpat** [comment]
Sorry for the late response. We will discuss about this issue recently.
