### ISSUE TITLE
Mismatched CUDA Version?

### ISSUE THREAD

**Issue by STF04** [Jumpat/SegmentAnythingin3D#64]
When attempting to download, and running the following line: 
"cd GroundingDINO/; pip install -e ."

I get this corresponding error:
    RuntimeError:
    The detected CUDA version (11.7) mismatches the version that was used to compile
    PyTorch (10.2). Please make sure to use the same CUDA versions.
    
Has anyone encountered this error and knows the solution, any help is greatly appreciated.

**Comment by Jumpat** [comment]
Hi, uninstall torch and try this. pip install torch==1.12.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117

**Comment by zratclif** [comment]
I am also having troubles with this; I get the same error. I entered the command you commented, and I get the following error:
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu117 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.0+cu117, 1.13.1, 1.13.1+cu117, 2.0.0, 2.0.0+cu117, 2.0.1, 2.0.1+cu117, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==1.12.1+cu117

**Comment by Jumpat** [comment]
> I am also having troubles with this; I get the same error. I entered the command you commented, and I get the following error:
> ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu117 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.0+cu117, 1.13.1, 1.13.1+cu117, 2.0.0, 2.0.0+cu117, 2.0.1, 2.0.1+cu117, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
> ERROR: No matching distribution found for torch==1.12.1+cu117

@zratclif This error is always disturbing😂. I think you can try to install another version of torch compiled with cu117. Our code does not have strict constrain on torch version.

**Comment by zratclif** [comment]
Thank you, that part finally worked. I have encountered another error: 'Segmentation fault (core dumped)' . This happens when I try to train NERF, which is running this command 'python run.py --config=configs/llff/fern.py --stop_at=20000 --render_video --i_weights=10000'. Do you know what could be the cause to this error? Thanks again for the help.

**Comment by Jumpat** [comment]
> Thank you, that part finally worked. I have encountered another error: 'Segmentation fault (core dumped)' . This happens when I try to train NERF, which is running this command 'python run.py --config=configs/llff/fern.py --stop_at=20000 --render_video --i_weights=10000'. Do you know what could be the cause to this error? Thanks again for the help.

Nope. @zratclif You may have to check the cuda version, PyTorch version and so on. I think this is caused by the wrongly complied cuda extension. Segmentation fault is always the last problem we want to meet.😂

**Comment by AsaKal** [comment]
Hi i am getting ` OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory`.  My system has cuda version 12.1

**Comment by Jumpat** [comment]
> Hi i am getting ` OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory`. My system has cuda version 12.1

@AsaKal 12.1 is too high. You may need 11.7. You can refer to the repo of 3D-GS for more information.

**Comment by AsaKal** [comment]
Okay thanks @Jumpat i will check it out
