### ISSUE TITLE
Thanks for supporting MobileSAM in your project.

### ISSUE THREAD

**Issue by ChaoningZhang** [Jumpat/SegmentAnythingin3D#7]
Thanks for supporting MobileSAM in your project. We have just recognized your effort in the readme of our project: https://github.com/ChaoningZhang/MobileSAM

**Comment by Jumpat** [comment]
You are welcome! MobileSAM does help SA3D to be faster and the 3D consistency in SA3D can refine the segmentation results of  MobileSAM. Hope such integration could benefit following studies.
