### ISSUE TITLE
KeyError: 'fl_x'

### ISSUE THREAD

**Issue by dadaaichifan** [Jumpat/SegmentAnythingin3D#81]
![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/171020146/8ee65fcb-6456-42e0-90b9-29c879898e78)
我在应用自己的数据集碰到了上述错误，我用colmap生成的，所以我应用了lerf_default.py。
下面是我的gaizhui.py
![image](https://github.com/Jumpat/SegmentAnythingin3D/assets/171020146/4898ddd8-b32a-428d-896a-3a52229aac67)
十分期待您解决我碰到的问题，谢谢您😊

**Comment by JacksonTao888** [comment]
你好，请问你是怎么解决这个问题的？

**Comment by jaz404** [comment]
> 你好，请问你是怎么解决这个问题的？

load_lerf.py expects fl_y and fl_x to be defined in every frame in transforms.json 
replace these lines in load_lerf.py:
```
  K = np.array([
           [frame['fl_x']/factor, 0, frame['cx']/factor],
           [0, frame['fl_y']/factor, frame['cy']/factor],
           [0, 0, 1]
       ]).astype(np.float32)
```
with: 
```
K = np.array([
    [metas['fl_x']/factor, 0, metas['cx']/factor],
    [0, metas['fl_y']/factor, metas['cy']/factor],
    [0, 0, 1]
]).astype(np.float32)

```
This should fix it!
