### ISSUE TITLE
coarse_segmentation_gui.tar文件结构

### ISSUE THREAD

**Issue by dadaaichifan** [Jumpat/SegmentAnythingin3D#83]
请问这个文件里包含什么信息？data.pkl和data文件夹分别存储什么信息？

**Comment by Jumpat** [comment]
可以参考[这部分代码](https://github.com/Jumpat/SegmentAnythingin3D/blob/b25698cbc7ca8e71b73749685b36f2914d6cbee7/lib/sam3d.py#L207)来确定其中保存的内容。grid和data没有关系。
