### ISSUE TITLE
Not segmenting

### ISSUE THREAD

**Issue by XinyangHan** [Jumpat/SegmentAnythingin3D#9]
I tried prompting using point and text, get the mask0,1,2, choose one mask, click 'generate'. But I the SAM part is always black screen and in the terminal it shows: tmp min: tensor(0.) tmp max: tensor(0.) No prompt is available. I am wondering how to solve this? Thank you so much for help!

**Comment by Jumpat** [comment]
Can you provide more information about this? Such as the scene you used, the segmentation target and the corresponding prompts, the first SAM mask. "tmp min: tensor(0.) tmp max: tensor(0.) " usually means the 3D mask grids initialization failed.

**Comment by XinyangHan** [comment]
Sure! I am using mip-nerf scene, and choose the table. prompt is 'table' and the mask0,1,2 look reasonable. (thanks so much for instant replying!)

**Comment by Zanue** [comment]
Can you post the full command for running this scene? We tested in this scene before and things seemed to be fine.

**Comment by XinyangHan** [comment]
Sure! 
The code for training nerf:
python run.py --config=configs/nerf_unbounded/garden.py --stop_at=20000 --render_video --i_weights=10000
The code for gui:
python run_seg_gui.py --config=configs/nerf_unbounded/garden.py --segment \
--sp_name=_gui --num_prompts=20 \
--render_opt=train --save_ckpt

**Comment by Jumpat** [comment]
Please check the config used in segmentation phase, which should be different from the nerf training. That is … --config=configs/nerf_unbounded/seg_garden.py … This adds optimizer for the mask grids.

**Comment by XinyangHan** [comment]
Thank u so much!!
